### ISSUE TITLE
Format error when checking checking user existence at login

### ISSUE THREAD

**Issue by ghost** [stevdza-san/BlogMultiplatform#1]
Dear Stevdza-san,

Thank you for the amazing tutorial. I'm having trouble with the login page (http://localhost:8080/admin/login)

I'm using your current code in the main branch (directly downloaded from git), with the local collections you posted in the course.

Even when the user exists I get the following error:
`
Expected start of the object '{', but had 'EOF' instead at path: $`

(in the Firefox Inspect Console). I've also attached a screenshot of what I am seeing in case that could be useful.

I did spend quite some time on it but couldn't find a solution. The article posts are loading correctly so I doubt the problem is with the way the database is set. As far as I could debug, the problem seems to come from 

```
window.api.tryPost(
            apiPath = "usercheck",
            body = Json.encodeToString(user).encodeToByteArray()
        )
```

in [ApiFunctions.kt](https://github.com/stevdza-san/BlogMultiplatform/blob/master/site/src/jsMain/kotlin/com/example/blogmultiplatform/util/ApiFunctions.kt) , perhaps it's a JSON / data class format issue.

![Screenshot 2023-10-06 at 13 52 22](https://github.com/stevdza-san/BlogMultiplatform/assets/125635037/acded361-4b8d-4aa3-8109-97797f651268)

**Comment by stevdza-san** [comment]
Hi there,

You need to debug and log the result from your serialization/deserialization process. And there you'll probably find your issue? You need to see how you're data is being serialized, to figure out what's happening behind the scenes actually.

**Comment by ghost** [comment]
It's a bug. When you use the correct password, it works. When you input a wrong password, you get the error I mentioned in my previous message and error message on the screen is "this user doesn't exist".

**Comment by ghost** [comment]
Sorry, I didn't realize the case where the user exists but the password is wrong is implement.
So it's is working as expected.

Closing the issue.
